name: build
on:
  push:
    tags: ["v*"] # タグpushでリリースまで実行
  workflow_dispatch: # 手動実行可（ただし release ジョブは if で抑制）

permissions:
  contents: write # リリース作成に必要

jobs:
  pyinstaller:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build from spec
        shell: bash
        run: |
          # ルート直下に WavLoopInspector.spec がある前提
          pyinstaller WavLoopInspector.spec

      # ---- pack artifacts ----
      - name: Zip (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Compress-Archive -Path dist\wavloop_inspect.exe -DestinationPath wavloop_win.zip -Force

      - name: Zip (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          ditto -c -k --sequesterRsrc --keepParent "dist/WavLoopInspector.app" "wavloop_mac.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-zip
          path: |
            wavloop_win.zip
            wavloop_mac.zip

  release:
    needs: pyinstaller
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') # 手動起動時はスキップ
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: "*-zip"
          merge-multiple: true
          path: ./artifacts

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
